### ISSUE TITLE
The prefix is empty

### ISSUE THREAD

**Issue by Eworm** [mariovass/statamic-uuid#8]
I've got a situation where the prefix remains empty. What info do you need from me to try to fix this?

**Comment by aryehraber** [comment]
Hey @Eworm, thanks for reporting! Haven't been keeping up with testing this addon on latest Statamic versions so will try to check it out soon!

Are you on the latest version of Statamic? And what browser (+ version) are you using? 

@edalzell Have you noticed any issues with the `prefix` option lately?

**Comment by Eworm** [comment]
Yeah, I'm on the latest version. I use Chrome 88.0.etc (latest version). The UUID fieldtype is in a fieldset, inside a replicator.

**Comment by aryehraber** [comment]
@Eworm Ok cool, thanks for checking! I was able to quickly recreate the issue on my end so can try fix it when I next have some available time. PRs are welcome if you're able to fix it sooner 😁

**Comment by aryehraber** [comment]
Looks like Statamic started using the `prefix` option at some point making it unusable by fieldtypes, it worked during the beta but has been untested since, so thanks for bringing this to my attention! 

The config option has now changed to `id_prefix` — I've updated the README to reflect this change.

Update has been tagged so should be available shortly via Marketplace/Composer.

**Comment by Eworm** [comment]
Nice!
